import { Metadata } from "next";
import ProductEditPage from "./ProductEditPage";

export const metadata: Metadata = {
  title: "Product",
  description: "Generated by create next app",
};

type Props = {
  params: Promise<{ productId: string }>;
};

async function Page({ params }: Props) {
  const { productId } = await params;
  return <ProductEditPage productId={productId} />;
}

export default Page;
