import type { Metadata } from "next";
import { setRequestLocale } from "next-intl/server";
import React, { use } from "react";

export const metadata: Metadata = {
  title: "Sign In",
  description: "Generated by create next app",
};

function SignInLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = use(params);

  // Enable static rendering for this locale
  setRequestLocale(locale);

  return <div>{children}</div>;
}

export default SignInLayout;
