import { Metadata } from "next"
import ProductsPage from "./ProductsPage"

export const metadata: Metadata = {
  title: "Products",
  description: "Generated by create next app",
}

function Page() {
  return (
    <ProductsPage/>
  )
}

export default Page