import ProductCreateForm from "./components/ProductCreateForm";
import BackButton from "../../../components/common/BackButton";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "New Product",
  description: "Generated by create next app",
}

function NewProductPage() {
  return (
    <div>
      <div className="flex flex-wrap items-center justify-between gap-8 mb-6 w-full">
        <h2 className="text-xl font-semibold text-gray-800 dark:text-white/90">
          Create New Product
        </h2>
        <BackButton />
      </div>
      <ProductCreateForm />
    </div>
  );
}

export default NewProductPage;
