import { SidebarProvider } from "@/context/admin/SidebarContext";
import { ThemeProvider } from "@/context/admin/ThemeContext";
import { createClient } from "@/lib/supabase/server";
import type { Metadata } from "next";
import { setRequestLocale } from "next-intl/server";
import { notFound, redirect } from "next/navigation";
import AppSidebar from "./layout/AppSidebar";
import Backdrop from "./layout/Backdrop";
import MainContent from "./MainContent";
import "./admin-globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { getFontClassName } from "@/lib/utils";
import { getLangDir } from "rtl-detect";
import { UserProvider } from "@/context/UserContext";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

async function AdminDashboardLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  // Protected route
  const supabase = await createClient();

  const {
    data: { user },
    error,
  } = await supabase.auth.getUser();
  const { data: profile } = await supabase
    .from("profiles")
    .select("role")
    .eq("id", user?.id)
    .single();

  if (error || !user) {
    redirect("/sign-in");
  }

  if (profile?.role !== "admin") {
    redirect("/");
  }

  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Enable static rendering for this locale
  setRequestLocale(locale);

  const fontClassName = getFontClassName(locale);
  const direction = getLangDir(locale);

  return (
    <html lang={locale} dir={direction}>
      <body className={`${fontClassName} antialiased dark:bg-gray-900`}>
        <NextIntlClientProvider>
          <UserProvider>
            <ThemeProvider>
              <SidebarProvider>
                <Toaster richColors />
                <div className="min-h-screen xl:flex">
                  {/* Sidebar and Backdrop */}
                  <AppSidebar />
                  <Backdrop />
                  {/* Main Content Area */}
                  <MainContent>{children}</MainContent>
                </div>
              </SidebarProvider>
            </ThemeProvider>
          </UserProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

export default AdminDashboardLayout;
