import { createClient } from "@/lib/supabase/server";
import type { Metadata } from "next";
import { setRequestLocale } from "next-intl/server";
import { notFound, redirect } from "next/navigation";
import AppSidebar from "./layout/AppSidebar";
import Backdrop from "./layout/Backdrop";
import MainContent from "./MainContent";
import "./admin-globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { getFontClassName } from "@/lib/utils";
import { getLangDir } from "rtl-detect";
import { Toaster } from "sonner";
import { getCurrentUser } from "@/lib/getCurrentUser";
import AdminProviders from "./AdminProviders";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

// const queryClient = new QueryClient();

async function AdminDashboardLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const currentUser = await getCurrentUser();
  const supabase = await createClient();

  const {
    data: { user },
    error,
  } = await supabase.auth.getUser();

  // Get CurrentUser role
  const { data: profile } = await supabase
    .from("profiles")
    .select("role")
    .eq("user_id", user?.id)
    .single();

  // Redirect to sign in if CurrentUser is null
  if (error || !user) {
    redirect("/sign-in");
  }

  // Redirect to home page if CurrentUser role is not admin
  if (profile?.role !== "admin") {
    redirect("/");
  }

  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Enable static rendering for this locale
  setRequestLocale(locale);

  const fontClassName = getFontClassName(locale);
  const direction = getLangDir(locale);

  return (
    <html lang={locale} dir={direction}>
      <body className={`${fontClassName} antialiased dark:bg-gray-900`}>
        <NextTopLoader color="#00b8db" />
        <NextIntlClientProvider>
          <AdminProviders>
            <Toaster richColors />
            <div className="min-h-screen xl:flex">
              {/* Sidebar and Backdrop */}
              <AppSidebar />
              <Backdrop />
              {/* Main Content Area */}
              <MainContent currentUserName={currentUser?.full_name}>
                {children}
              </MainContent>
            </div>
          </AdminProviders>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

export default AdminDashboardLayout;
