import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Statistics",
  description: "Generated by create next app",
};

export default function StatisticsPage() {
  return (
    <div>
      <h1 className="text-2xl dark:text-white">Statistics Page</h1>
    </div>
  );
}
