import type { Metadata } from "next";
import { login } from "../actions";
import { setRequestLocale } from "next-intl/server";
import { use } from "react";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function LoginPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = use(params);

  // Enable static rendering for this locale
  setRequestLocale(locale);

  return (
    <form className="flex flex-col gap-4">
      <h2 className="text-2xl font-bold">Login</h2>
      <label htmlFor="email">Email</label>
      <input name="email" type="email" required className="border p-2" />

      <label htmlFor="password">Password</label>
      <input name="password" type="password" required className="border p-2" />
      
      <Button formAction={login} className="p-2 py-5 rounded text-base font-normal">
        Sign In
      </Button>
    </form>
  );
}
