import type { Metadata } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { getFontClassName } from "@/lib/utils/getFontClassName";
import { getLangDir } from "rtl-detect";
import { Toaster } from "sonner";
import PublicProviders from "./PublicProviders";
import NextTopLoader from "nextjs-toploader";

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: "Shopya",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: Readonly<React.ReactNode>;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Enable static rendering for this locale
  setRequestLocale(locale);

  const fontClassName = getFontClassName(locale);
  const direction = getLangDir(locale);

  return (
    <html lang={locale} dir={direction}>
      <body className={`${fontClassName} antialiased`}>
        <NextTopLoader color="#00b8db"/>
        <NextIntlClientProvider>
          <PublicProviders>
            <Toaster richColors />
            {children}
          </PublicProviders>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
