import { Metadata } from "next";
import UserEditPage from "./UserEditPage";

type Props = {
  params: Promise<{ userId: string }>;
};

export const metadata: Metadata = {
  title: "User",
  description: "Generated by create next app",
}

async function Page({ params }: Props) {
  const { userId } = await params;
  return <UserEditPage userId={userId}/>;
}

export default Page;
