import { Metadata } from "next"
import OrdersPage from "./OrdersPage"

export const metadata: Metadata = {
  title: "Orders",
  description: "Generated by create next app",
}

function Page() {
  return (
    <OrdersPage/>
  )
}

export default Page