import type { Metadata } from 'next';
import UsersPage from './UsersPage';

export const metadata: Metadata = {
  title: "Users",
  description: "Generated by create next app",
};

function Page() {
  return (
    <UsersPage/>
  )
}

export default Page