import { Metadata } from "next"
import CategoriesPage from "./CategoriesPage"

export const metadata: Metadata = {
  title: "Categories",
  description: "Generated by create next app",
}

function Page() {
  return (
    <CategoriesPage/>
  )
}

export default Page