import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./(public)/components/Navbar";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { getFontClassName } from "@/lib/utils";
import { getLangDir } from "rtl-detect";

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: Readonly<React.ReactNode>;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Enable static rendering for this locale
  setRequestLocale(locale);

  const fontClassName = getFontClassName(locale);
  const direction = getLangDir(locale);

  return (
    <html lang={locale} dir={direction}>
      <body className={`${fontClassName} antialiased`}>
        <NextIntlClientProvider>
          <div
            aria-label="banner"
            className="bg-black text-white text-center py-2 text-[14px] font-light"
          >
            Sign up and get 20% off to your first order.{" "}
            <span className="underline font-normal">Sign Up Now</span>
          </div>
          <Navbar />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
