import { Metadata } from 'next';
import CategoryEditPage from './CategoryEditPage';

export const metadata: Metadata = {
  title: "Category",
  description: "Generated by create next app",
}

async function Page({ params }: { params: Promise<{ categoryId: string }> }) {
  const { categoryId } = await params;
  return (
    <CategoryEditPage categoryId={categoryId}/>
  )
}

export default Page